// Barrel for every route contract. Adding a new contract? Re-export it here
// so consumers can pull it from a single specifier.
export { calendarDataContract } from './calendar-data.contract'
export { equipmentTypesContract } from './equipment-types.contract'
export { catalogExerciseSchema } from './exercise.schema'
export { exerciseCategoriesContract } from './exercise-categories.contract'
export { exerciseFavoritesContract } from './exercise-favorites.contract'
export { exercisesRecentContract } from './exercises.recent.contract'
export { exercisesSearchContract } from './exercises.search.contract'
export { exercisesSuggestedContract } from './exercises.suggested.contract'
export { muscleGroupsContract } from './muscle-groups.contract'
export { nextWorkoutContract } from './next-workout.contract'
export { progressContract } from './progress.contract'
export { workoutDetailsContract } from './workout-details.contract'
export { workoutSessionsContract } from './workout-sessions.contract'
export { workoutSetsContract } from './workout-sets.contract'
export { workoutTemplatesContract } from './workout-templates.contract'
