// Supabase-backed query module for private workout sets.
//
// Mirrors `workoutSetQueries` from src/lib/database/queries/workouts.ts.
// Ownership is enforced transitively by RLS — a workout set belongs to the
// authenticated user iff its parent workout_session.user_id = auth.uid().
// Callers must use a request-scoped Supabase client; these functions never
// take a userId. Ids are generated by Postgres (`gen_random_uuid()`).
//
// The SQLite WorkoutSetInput exposes a `set_order` field that maps to the
// Postgres `set_number` column — that mapping is preserved here so the route
// contracts stay stable.

import type { SupabaseClient } from '@supabase/supabase-js'
import type { WorkoutSet, WorkoutSetInput } from '../../types/database'
import type { Database } from '../database.types'

type SB = SupabaseClient<Database> | SupabaseClient<any, 'public', any>

type SetRow = {
  id: string
  workout_id: string
  exercise_id: string
  set_number: number
  weight: number | null
  reps: number | null
  rest_time: number | null
  notes: string | null
  created_at: string
  updated_at: string
}

function mapSet(row: SetRow): WorkoutSet {
  return {
    id: row.id,
    workout_id: row.workout_id,
    exercise_id: row.exercise_id,
    set_number: row.set_number,
    weight: row.weight ?? undefined,
    reps: row.reps ?? undefined,
    rest_time: row.rest_time ?? undefined,
    notes: row.notes ?? undefined,
    created_at: new Date(row.created_at),
    updated_at: new Date(row.updated_at),
  }
}

const SET_COLUMNS =
  'id, workout_id, exercise_id, set_number, weight, reps, rest_time, notes, created_at, updated_at'

export const workoutSetQueries = {
  async getById(supabase: SB, id: string): Promise<WorkoutSet | null> {
    const { data, error } = await (supabase as any)
      .from('workout_sets')
      .select(SET_COLUMNS)
      .eq('id', id)
      .maybeSingle()

    if (error) throw error
    if (!data) return null
    return mapSet(data as SetRow)
  },

  // All sets for a given workout, ordered by set_number then insertion time.
  // RLS filters to sets belonging to sessions owned by the caller.
  async listByWorkoutId(supabase: SB, workoutId: string): Promise<WorkoutSet[]> {
    const { data, error } = await (supabase as any)
      .from('workout_sets')
      .select(SET_COLUMNS)
      .eq('workout_id', workoutId)
      .order('set_number', { ascending: true })
      .order('created_at', { ascending: true })

    if (error) throw error
    return ((data ?? []) as SetRow[]).map(mapSet)
  },

  // Create a new set. The parent session must be owned by the authenticated
  // user — otherwise the insert is rejected by RLS and we surface that to the
  // caller. `set_order` is the legacy input field name; it maps to
  // `set_number` in Postgres.
  async create(supabase: SB, data: WorkoutSetInput): Promise<WorkoutSet> {
    const insertRow = {
      workout_id: data.workout_id,
      exercise_id: data.exercise_id,
      set_number: data.set_order,
      reps: data.reps ?? null,
      weight: data.weight ?? null,
      rest_time: data.rest_time ?? null,
      notes: data.notes ?? null,
    }

    const { data: row, error } = await (supabase as any)
      .from('workout_sets')
      .insert(insertRow)
      .select(SET_COLUMNS)
      .single()

    if (error) throw error
    return mapSet(row as SetRow)
  },

  async update(
    supabase: SB,
    id: string,
    data: Partial<WorkoutSetInput>,
  ): Promise<WorkoutSet | null> {
    const patch: Record<string, unknown> = {}
    if (data.set_order !== undefined) patch.set_number = data.set_order
    if (data.reps !== undefined) patch.reps = data.reps
    if (data.weight !== undefined) patch.weight = data.weight
    if (data.rest_time !== undefined) patch.rest_time = data.rest_time
    if (data.notes !== undefined) patch.notes = data.notes

    if (Object.keys(patch).length === 0) {
      return workoutSetQueries.getById(supabase, id)
    }

    const { data: row, error } = await (supabase as any)
      .from('workout_sets')
      .update(patch)
      .eq('id', id)
      .select(SET_COLUMNS)
      .maybeSingle()

    if (error) throw error
    if (!row) return null
    return mapSet(row as SetRow)
  },

  async delete(supabase: SB, id: string): Promise<boolean> {
    const { data, error } = await (supabase as any)
      .from('workout_sets')
      .delete()
      .eq('id', id)
      .select('id')

    if (error) throw error
    return Array.isArray(data) && data.length > 0
  },

  // Remove every set for a given exercise from a given workout. Used by the
  // workout UI's "Remove Exercise" button. RLS keeps the delete scoped to the
  // user's own workouts.
  async deleteByExercise(supabase: SB, workoutId: string, exerciseId: string): Promise<number> {
    const { data, error } = await (supabase as any)
      .from('workout_sets')
      .delete()
      .eq('workout_id', workoutId)
      .eq('exercise_id', exerciseId)
      .select('id')

    if (error) throw error
    return Array.isArray(data) ? data.length : 0
  },
}
