/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts.new'
import { Route as WorkoutsTemplateIdEditRouteImport } from './routes/workouts.$templateId.edit'
import { ServerRoute as AuthCallbackServerRouteImport } from './routes/auth.callback'
import { ServerRoute as ApiWorkoutTemplatesServerRouteImport } from './routes/api.workout-templates'
import { ServerRoute as ApiWorkoutSetsServerRouteImport } from './routes/api.workout-sets'
import { ServerRoute as ApiWorkoutSessionsServerRouteImport } from './routes/api.workout-sessions'
import { ServerRoute as ApiWorkoutDetailsServerRouteImport } from './routes/api.workout-details'
import { ServerRoute as ApiProgressServerRouteImport } from './routes/api.progress'
import { ServerRoute as ApiNextWorkoutServerRouteImport } from './routes/api.next-workout'
import { ServerRoute as ApiMuscleGroupsServerRouteImport } from './routes/api.muscle-groups'
import { ServerRoute as ApiExerciseFavoritesServerRouteImport } from './routes/api.exercise-favorites'
import { ServerRoute as ApiExerciseCategoriesServerRouteImport } from './routes/api.exercise-categories'
import { ServerRoute as ApiEquipmentTypesServerRouteImport } from './routes/api.equipment-types'
import { ServerRoute as ApiCalendarDataServerRouteImport } from './routes/api.calendar-data'
import { ServerRoute as ApiExercisesSuggestedServerRouteImport } from './routes/api.exercises.suggested'
import { ServerRoute as ApiExercisesSearchServerRouteImport } from './routes/api.exercises.search'
import { ServerRoute as ApiExercisesRecentServerRouteImport } from './routes/api.exercises.recent'

const rootServerRouteImport = createServerRootRoute()

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsTemplateIdEditRoute = WorkoutsTemplateIdEditRouteImport.update({
  id: '/$templateId/edit',
  path: '/$templateId/edit',
  getParentRoute: () => WorkoutsRoute,
} as any)
const AuthCallbackServerRoute = AuthCallbackServerRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiWorkoutTemplatesServerRoute =
  ApiWorkoutTemplatesServerRouteImport.update({
    id: '/api/workout-templates',
    path: '/api/workout-templates',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiWorkoutSetsServerRoute = ApiWorkoutSetsServerRouteImport.update({
  id: '/api/workout-sets',
  path: '/api/workout-sets',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiWorkoutSessionsServerRoute =
  ApiWorkoutSessionsServerRouteImport.update({
    id: '/api/workout-sessions',
    path: '/api/workout-sessions',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiWorkoutDetailsServerRoute = ApiWorkoutDetailsServerRouteImport.update({
  id: '/api/workout-details',
  path: '/api/workout-details',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiProgressServerRoute = ApiProgressServerRouteImport.update({
  id: '/api/progress',
  path: '/api/progress',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiNextWorkoutServerRoute = ApiNextWorkoutServerRouteImport.update({
  id: '/api/next-workout',
  path: '/api/next-workout',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMuscleGroupsServerRoute = ApiMuscleGroupsServerRouteImport.update({
  id: '/api/muscle-groups',
  path: '/api/muscle-groups',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiExerciseFavoritesServerRoute =
  ApiExerciseFavoritesServerRouteImport.update({
    id: '/api/exercise-favorites',
    path: '/api/exercise-favorites',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiExerciseCategoriesServerRoute =
  ApiExerciseCategoriesServerRouteImport.update({
    id: '/api/exercise-categories',
    path: '/api/exercise-categories',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiEquipmentTypesServerRoute = ApiEquipmentTypesServerRouteImport.update({
  id: '/api/equipment-types',
  path: '/api/equipment-types',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiCalendarDataServerRoute = ApiCalendarDataServerRouteImport.update({
  id: '/api/calendar-data',
  path: '/api/calendar-data',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiExercisesSuggestedServerRoute =
  ApiExercisesSuggestedServerRouteImport.update({
    id: '/api/exercises/suggested',
    path: '/api/exercises/suggested',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiExercisesSearchServerRoute =
  ApiExercisesSearchServerRouteImport.update({
    id: '/api/exercises/search',
    path: '/api/exercises/search',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiExercisesRecentServerRoute =
  ApiExercisesRecentServerRouteImport.update({
    id: '/api/exercises/recent',
    path: '/api/exercises/recent',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/workouts/$templateId/edit': typeof WorkoutsTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/workouts/$templateId/edit': typeof WorkoutsTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/workouts/$templateId/edit': typeof WorkoutsTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/history'
    | '/progress'
    | '/workout'
    | '/workouts'
    | '/workouts/new'
    | '/workouts/'
    | '/workouts/$templateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/history'
    | '/progress'
    | '/workout'
    | '/workouts/new'
    | '/workouts'
    | '/workouts/$templateId/edit'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/history'
    | '/progress'
    | '/workout'
    | '/workouts'
    | '/workouts/new'
    | '/workouts/'
    | '/workouts/$templateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRoute
  HistoryRoute: typeof HistoryRoute
  ProgressRoute: typeof ProgressRoute
  WorkoutRoute: typeof WorkoutRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/calendar-data': typeof ApiCalendarDataServerRoute
  '/api/equipment-types': typeof ApiEquipmentTypesServerRoute
  '/api/exercise-categories': typeof ApiExerciseCategoriesServerRoute
  '/api/exercise-favorites': typeof ApiExerciseFavoritesServerRoute
  '/api/muscle-groups': typeof ApiMuscleGroupsServerRoute
  '/api/next-workout': typeof ApiNextWorkoutServerRoute
  '/api/progress': typeof ApiProgressServerRoute
  '/api/workout-details': typeof ApiWorkoutDetailsServerRoute
  '/api/workout-sessions': typeof ApiWorkoutSessionsServerRoute
  '/api/workout-sets': typeof ApiWorkoutSetsServerRoute
  '/api/workout-templates': typeof ApiWorkoutTemplatesServerRoute
  '/auth/callback': typeof AuthCallbackServerRoute
  '/api/exercises/recent': typeof ApiExercisesRecentServerRoute
  '/api/exercises/search': typeof ApiExercisesSearchServerRoute
  '/api/exercises/suggested': typeof ApiExercisesSuggestedServerRoute
}
export interface FileServerRoutesByTo {
  '/api/calendar-data': typeof ApiCalendarDataServerRoute
  '/api/equipment-types': typeof ApiEquipmentTypesServerRoute
  '/api/exercise-categories': typeof ApiExerciseCategoriesServerRoute
  '/api/exercise-favorites': typeof ApiExerciseFavoritesServerRoute
  '/api/muscle-groups': typeof ApiMuscleGroupsServerRoute
  '/api/next-workout': typeof ApiNextWorkoutServerRoute
  '/api/progress': typeof ApiProgressServerRoute
  '/api/workout-details': typeof ApiWorkoutDetailsServerRoute
  '/api/workout-sessions': typeof ApiWorkoutSessionsServerRoute
  '/api/workout-sets': typeof ApiWorkoutSetsServerRoute
  '/api/workout-templates': typeof ApiWorkoutTemplatesServerRoute
  '/auth/callback': typeof AuthCallbackServerRoute
  '/api/exercises/recent': typeof ApiExercisesRecentServerRoute
  '/api/exercises/search': typeof ApiExercisesSearchServerRoute
  '/api/exercises/suggested': typeof ApiExercisesSuggestedServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/calendar-data': typeof ApiCalendarDataServerRoute
  '/api/equipment-types': typeof ApiEquipmentTypesServerRoute
  '/api/exercise-categories': typeof ApiExerciseCategoriesServerRoute
  '/api/exercise-favorites': typeof ApiExerciseFavoritesServerRoute
  '/api/muscle-groups': typeof ApiMuscleGroupsServerRoute
  '/api/next-workout': typeof ApiNextWorkoutServerRoute
  '/api/progress': typeof ApiProgressServerRoute
  '/api/workout-details': typeof ApiWorkoutDetailsServerRoute
  '/api/workout-sessions': typeof ApiWorkoutSessionsServerRoute
  '/api/workout-sets': typeof ApiWorkoutSetsServerRoute
  '/api/workout-templates': typeof ApiWorkoutTemplatesServerRoute
  '/auth/callback': typeof AuthCallbackServerRoute
  '/api/exercises/recent': typeof ApiExercisesRecentServerRoute
  '/api/exercises/search': typeof ApiExercisesSearchServerRoute
  '/api/exercises/suggested': typeof ApiExercisesSuggestedServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/calendar-data'
    | '/api/equipment-types'
    | '/api/exercise-categories'
    | '/api/exercise-favorites'
    | '/api/muscle-groups'
    | '/api/next-workout'
    | '/api/progress'
    | '/api/workout-details'
    | '/api/workout-sessions'
    | '/api/workout-sets'
    | '/api/workout-templates'
    | '/auth/callback'
    | '/api/exercises/recent'
    | '/api/exercises/search'
    | '/api/exercises/suggested'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/calendar-data'
    | '/api/equipment-types'
    | '/api/exercise-categories'
    | '/api/exercise-favorites'
    | '/api/muscle-groups'
    | '/api/next-workout'
    | '/api/progress'
    | '/api/workout-details'
    | '/api/workout-sessions'
    | '/api/workout-sets'
    | '/api/workout-templates'
    | '/auth/callback'
    | '/api/exercises/recent'
    | '/api/exercises/search'
    | '/api/exercises/suggested'
  id:
    | '__root__'
    | '/api/calendar-data'
    | '/api/equipment-types'
    | '/api/exercise-categories'
    | '/api/exercise-favorites'
    | '/api/muscle-groups'
    | '/api/next-workout'
    | '/api/progress'
    | '/api/workout-details'
    | '/api/workout-sessions'
    | '/api/workout-sets'
    | '/api/workout-templates'
    | '/auth/callback'
    | '/api/exercises/recent'
    | '/api/exercises/search'
    | '/api/exercises/suggested'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiCalendarDataServerRoute: typeof ApiCalendarDataServerRoute
  ApiEquipmentTypesServerRoute: typeof ApiEquipmentTypesServerRoute
  ApiExerciseCategoriesServerRoute: typeof ApiExerciseCategoriesServerRoute
  ApiExerciseFavoritesServerRoute: typeof ApiExerciseFavoritesServerRoute
  ApiMuscleGroupsServerRoute: typeof ApiMuscleGroupsServerRoute
  ApiNextWorkoutServerRoute: typeof ApiNextWorkoutServerRoute
  ApiProgressServerRoute: typeof ApiProgressServerRoute
  ApiWorkoutDetailsServerRoute: typeof ApiWorkoutDetailsServerRoute
  ApiWorkoutSessionsServerRoute: typeof ApiWorkoutSessionsServerRoute
  ApiWorkoutSetsServerRoute: typeof ApiWorkoutSetsServerRoute
  ApiWorkoutTemplatesServerRoute: typeof ApiWorkoutTemplatesServerRoute
  AuthCallbackServerRoute: typeof AuthCallbackServerRoute
  ApiExercisesRecentServerRoute: typeof ApiExercisesRecentServerRoute
  ApiExercisesSearchServerRoute: typeof ApiExercisesSearchServerRoute
  ApiExercisesSuggestedServerRoute: typeof ApiExercisesSuggestedServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/$templateId/edit': {
      id: '/workouts/$templateId/edit'
      path: '/$templateId/edit'
      fullPath: '/workouts/$templateId/edit'
      preLoaderRoute: typeof WorkoutsTemplateIdEditRouteImport
      parentRoute: typeof WorkoutsRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/workout-templates': {
      id: '/api/workout-templates'
      path: '/api/workout-templates'
      fullPath: '/api/workout-templates'
      preLoaderRoute: typeof ApiWorkoutTemplatesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/workout-sets': {
      id: '/api/workout-sets'
      path: '/api/workout-sets'
      fullPath: '/api/workout-sets'
      preLoaderRoute: typeof ApiWorkoutSetsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/workout-sessions': {
      id: '/api/workout-sessions'
      path: '/api/workout-sessions'
      fullPath: '/api/workout-sessions'
      preLoaderRoute: typeof ApiWorkoutSessionsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/workout-details': {
      id: '/api/workout-details'
      path: '/api/workout-details'
      fullPath: '/api/workout-details'
      preLoaderRoute: typeof ApiWorkoutDetailsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/progress': {
      id: '/api/progress'
      path: '/api/progress'
      fullPath: '/api/progress'
      preLoaderRoute: typeof ApiProgressServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/next-workout': {
      id: '/api/next-workout'
      path: '/api/next-workout'
      fullPath: '/api/next-workout'
      preLoaderRoute: typeof ApiNextWorkoutServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/muscle-groups': {
      id: '/api/muscle-groups'
      path: '/api/muscle-groups'
      fullPath: '/api/muscle-groups'
      preLoaderRoute: typeof ApiMuscleGroupsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/exercise-favorites': {
      id: '/api/exercise-favorites'
      path: '/api/exercise-favorites'
      fullPath: '/api/exercise-favorites'
      preLoaderRoute: typeof ApiExerciseFavoritesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/exercise-categories': {
      id: '/api/exercise-categories'
      path: '/api/exercise-categories'
      fullPath: '/api/exercise-categories'
      preLoaderRoute: typeof ApiExerciseCategoriesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/equipment-types': {
      id: '/api/equipment-types'
      path: '/api/equipment-types'
      fullPath: '/api/equipment-types'
      preLoaderRoute: typeof ApiEquipmentTypesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/calendar-data': {
      id: '/api/calendar-data'
      path: '/api/calendar-data'
      fullPath: '/api/calendar-data'
      preLoaderRoute: typeof ApiCalendarDataServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/exercises/suggested': {
      id: '/api/exercises/suggested'
      path: '/api/exercises/suggested'
      fullPath: '/api/exercises/suggested'
      preLoaderRoute: typeof ApiExercisesSuggestedServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/exercises/search': {
      id: '/api/exercises/search'
      path: '/api/exercises/search'
      fullPath: '/api/exercises/search'
      preLoaderRoute: typeof ApiExercisesSearchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/exercises/recent': {
      id: '/api/exercises/recent'
      path: '/api/exercises/recent'
      fullPath: '/api/exercises/recent'
      preLoaderRoute: typeof ApiExercisesRecentServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface WorkoutsRouteChildren {
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  WorkoutsTemplateIdEditRoute: typeof WorkoutsTemplateIdEditRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsNewRoute: WorkoutsNewRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  WorkoutsTemplateIdEditRoute: WorkoutsTemplateIdEditRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRoute,
  HistoryRoute: HistoryRoute,
  ProgressRoute: ProgressRoute,
  WorkoutRoute: WorkoutRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiCalendarDataServerRoute: ApiCalendarDataServerRoute,
  ApiEquipmentTypesServerRoute: ApiEquipmentTypesServerRoute,
  ApiExerciseCategoriesServerRoute: ApiExerciseCategoriesServerRoute,
  ApiExerciseFavoritesServerRoute: ApiExerciseFavoritesServerRoute,
  ApiMuscleGroupsServerRoute: ApiMuscleGroupsServerRoute,
  ApiNextWorkoutServerRoute: ApiNextWorkoutServerRoute,
  ApiProgressServerRoute: ApiProgressServerRoute,
  ApiWorkoutDetailsServerRoute: ApiWorkoutDetailsServerRoute,
  ApiWorkoutSessionsServerRoute: ApiWorkoutSessionsServerRoute,
  ApiWorkoutSetsServerRoute: ApiWorkoutSetsServerRoute,
  ApiWorkoutTemplatesServerRoute: ApiWorkoutTemplatesServerRoute,
  AuthCallbackServerRoute: AuthCallbackServerRoute,
  ApiExercisesRecentServerRoute: ApiExercisesRecentServerRoute,
  ApiExercisesSearchServerRoute: ApiExercisesSearchServerRoute,
  ApiExercisesSuggestedServerRoute: ApiExercisesSuggestedServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
